apiVersion: v1
kind: Secret
metadata:
  name: shina-public-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Shinaayo07/argocd-assignment.git